global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:8088"]
    metrics_path: "/metrics"
