server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape logs from all Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Extract container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      # Extract container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'

      # Extract service name from container labels
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

      # Extract project name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'

      # Log stream (stdout/stderr)
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    # Pipeline stages to parse JSON logs
    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service_name: service
            instance_id: instance_id
            correlation_id: correlation_id
            message: message
            context: context
            error: error

      # Extract timestamp if present
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # Set labels from JSON fields
      - labels:
          level:
          service_name:
          correlation_id:

      # Output the message
      - output:
          source: message
