on:
    pull_request:
        types: [opened, edited, synchronize]

jobs:
    check_conventional_commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: webiny/action-conventional-commits@v1.0.3
